# Generated by Django 5.2.1 on 2025-06-10 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_dashboards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_dashboards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupdashboard",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_dashboard_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupdashboard",
            name="dashboards",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="dashboard_groups",
                to="dashboards.dashboard",
            ),
        ),
        migrations.AddField(
            model_name="groupdashboard",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="dashboard_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
