# Generated by Django 5.2.1 on 2025-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="status",
            field=models.CharField(default="sandbox", max_length=50),
        ),
    ]
