# Generated by Django 5.2.1 on 2025-06-05 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='dashboards',
            field=models.ManyToManyField(blank=True, null=True, related_name='dashboard_groups', to='dashboards.dashboard'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='dashboard_workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
