# Generated by Django 5.2.1 on 2025-06-26 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_dashboard_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="published",
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="status",
            field=models.CharField(
                choices=[("sandbox", "Sandbox"), ("published", "Published")],
                default="sandbox",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="groupdashboard",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="dashboard_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
