# Generated by Django 5.2.1 on 2025-07-04 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboards",
            "0004_remove_dashboard_published_alter_dashboard_status_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupdashboard",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="dashboard_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
