# Generated by Django 5.2.1 on 2025-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="URL to the user's avatar image.", max_length=2000, null=True),
        ),
    ]
