# Generated by Django 5.2.1 on 2025-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture_url',
            field=models.CharField(max_length=2000),
        ),
    ]
