# Generated by Django 5.2.1 on 2025-05-20 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='members',
            field=models.ManyToManyField(related_name='roles', through='users.UserRole', through_fields=('role', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role'),
        ),
    ]
